repo_database:
  chunk_overlap: 0
  chunk_size: 1000
  extension: py
  database_path: ./database
  database_type: table
  remove_docstr: False
  retriever_kwargs:
    search_type: similarity_score_threshold
    search_kwargs:
      k: 3
      score_threshold: 0.5

llm:
  n_ctx: 1024
  verbose: False
  f16_kv: True
  n_gpu_layers: 25
  max_tokens: 2048
  temperature: 0.75
  top_p: 1

agent:
  trim_context: True
  max_k: 5

external_database:
  database_path: None
  database_type: faiss
  retriever_kwargs:
    search_type: similarity_with_threshold
    search_kwargs:
    k: 3
    score_threshold: 0.5
